import type { ProductTranslation } from "./types";

export const finishTranslations: Record<string, string> = {
  "SKIN FINISH PERFECTED": "KULIT AUTO FLAWLESS",
  "FLAWLESS FLUSHED CHEEKS": "PIPI MERONA SEKETIKA",
  "BROWS, BUT BETTER": "ALIS ANTI BADAI",
  "EYE GAME STRONG": "EKSPLORASI EYE LOOK",
  "TINTED TO GO": "STAIN SESUAI MOODMU",
  "GLOSS IT BETTER": "GLOSSY TANPA BATAS",
  "IT'S MATTE TO LAST": "BOLD SEHARIAN TANPA TOUCH UP",
};

export const productTranslations: Record<string, ProductTranslation> = {
  "ALTERA LIP TINT": { description: "Lip color inovatif yang berubah dari tampilan glossy menjadi soft blurry hanya dengan satu swipe.", claims: ["Blur Garis Bibir", "Stain Tahan Lama", "Warna Intens"] },
  "ELIXIR VELVET-SHINE SWITCHING LIP CREAM": { description: "Lip velvet ringan dan melembapkan dengan dua hasil akhir dalam satu produk.", claims: ["2 Hasil Bibir", "Warna Intens", "Super Nyaman"] },
  "ETERNAL LIP MATTE": { description: "Lip matte dengan warna super pigmented dengan hasil transferproof dan waterproof hingga 24 jam.", claims: ["Hasil Bold Matte", "Warna Intens", "Feel Ringan"] },
  "NEBULA LIP CREAM": { description: "Lip bertekstur velvet-matte yang lembut, tidak membuat bibir terasa kering, dan menyamarkan garis bibir.", claims: ["Hasil Velvet Matte", "Anti Transfer", "Feel Ringan"] },
  "STELLAR DUST LIP STAIN": { description: "Full coverage dalam sekali swipe dengan tekstur ringan yang mengunci pigmen agar tahan lama dan tidak mudah transfer.", claims: ["Stain Super Intens", "Kilau Maksimal", "Tahan Lama"] },
  "SPECTRA LIP VINYL": { description: "Lip vinyl transfer-proof dengan warna ultra-intens dan full coverage hanya dalam satu swipe.", claims: ["Warna Intens", "Tahan 24 Jam", "Super Nyaman"] },
  "ORION CLOUD MATTE LIPSTICK": { description: "Lipstik matte blurring berpigmentasi tinggi dengan full coverage dan hasil transferproof hingga 12 jam.", claims: ["Matte Blur Halus", "Tekstur Lembut", "Anti Transfer"] },
  "ORBITA 3 IN 1 BLURRING POT": { description: "Bouncy velvet mud multifungsi untuk mata, pipi, dan bibir dengan aplikator silikon yang presisi.", claims: ["Hasil Velvet Blur", "Buildable", "Aplikator Praktis"] },
  "MILKYWAY MELTING LIP BALM": { description: "5D Shine Melting Balm bertekstur buttery dengan sensasi dingin, warna vibrant, dan hasil glossy seperti cermin.", claims: ["Kilau 5D", "Selembut Butter", "Menutrisi"] },
  "LUNARA 3D LIP GLOSS": { description: "Lip gloss bertekstur gel lembut dengan hasil high-shine seperti kaca.", claims: ["Efek Bibir 3D", "Anti Lengket", "Sensasi Dingin"] },
  "APHRODITE EVERLASTING GLOSSY TINT": { description: "Tint bibir berkilau dengan warna cerah dan stain tahan lama yang menjaga bibir nyaman dan terhidrasi.", claims: ["Tekstur Juicy", "Stain Water Lock", "Super Nyaman"] },
  "AION SUPERSTAIN LIP TATTOO INK": { description: "Tint gel cair dengan pigmen 3x lebih pekat yang memberikan warna intens hingga 24 jam.", claims: ["Warna Intens", "Tanpa Dikelupas", "Tahan Lama"] },
  "UTOPIA GLOW CUSHION": { description: "Glow cushion ringan dan ultra-hydrating dengan hasil glow-radiant instan, medium-full coverage, dan ketahanan hingga 10 jam.", claims: ["Hasil Glowing", "Halus Seketika", "Melembapkan"] },
  "LUMINA MATTE CUSHION": { description: "Cushion full coverage yang tetap ringan untuk tampilan natural dan flawless sepanjang hari.", claims: ["Hasil Natural", "Feel Ringan", "Anti Oksidasi"] },
  "OPTIMA POWDER FOUNDATION": { description: "Powder foundation ekstra-ringan yang memberikan full coverage hanya dengan satu usapan.", claims: ["Hasil Blur Matte", "Kontrol Minyak", "Non-Komedogenik"] },
  "PANDORA CHEEK LIQUID BLUSH": { description: "Blush berpigmentasi tinggi yang memberikan warna intens hanya dengan satu titik.", claims: ["Warna Intens", "Mudah di-Blend", "Tahan Lama"] },
  "FIXION SKIN TINT STICK": { description: "Skin tint stick creamy dan ringan dengan medium hingga full coverage serta hasil second-skin hingga 8 jam.", claims: ["Hasil Satin", "Tekstur Creamy", "Ringan di Kulit"] },
  "ECLIPSE 2 IN 1 FACE CONTOUR": { description: "Stik kontur wajah 2-in-1 dengan formula ultra-creamy dan warna intens yang mulus dalam satu swipe.", claims: ["Super Creamy", "Krim ke Powder", "Brush Lepas-Pasang"] },
  "VALORA CONCEALER": { description: "Concealer coverage tinggi yang menyamarkan dark circle dan imperfection dengan hasil ringan dan tahan crease hingga 12 jam.", claims: ["Hasil Soft Matte", "Pigmen Intens", "Melembapkan"] },
  "SUPERNOVA SETTING SPRAY": { description: "Setting spray dengan partikel powder halus dan merata untuk makeup yang instant matte dan shine-free.", claims: ["Hasil Matte", "Anti Luntur", "Kontrol Minyak"] },
  "REVELA BROW MASCARA": { description: "Mascara alis dengan pigmen intens dan holding power yang kuat.", claims: ["Warna Intens", "Tahan 12 Jam", "Anti Gumpal"] },
  "ILLUMINA EYESHADOW STICK": { description: "Eyeshadow stick bertekstur jelly yang ringan dan mudah diaplikasikan dengan warna intens dan high shine dalam sekali swipe.", claims: ["Tekstur Jelly", "Kilau Seketika", "Anti Fallout"] },
  "DUNE EYELINER": { description: "Eyeliner dengan aplikator tipis dan presisi untuk membuat garis yang akurat dan rapi.", claims: ["Pigmen Bold", "Ujung Presisi", "Tahan Air"] },
  "GENESIS EYEBROW PENCIL": { description: "Pensil alis berujung oval presisi untuk membingkai, mengisi, dan mendefinisikan alis natural maupun bold.", claims: ["Hasil Natural", "Ujung Oval", "Anti Luntur"] },
  "NAVI EYESHADOW PALETTE": { description: "Palet eyeshadow 8 warna matte, satin, dan shimmer yang mudah dibaurkan untuk tampilan tahan lama.", claims: ["Warna Intens", "Mudah di-Blend", "Tahan Lama"] },
};

export const finishTranslationsSpanish: Record<string, string> = {
  "SKIN FINISH PERFECTED": "PIEL PERFECCIONADA",
  "FLAWLESS FLUSHED CHEEKS": "MEJILLAS RADIANTES",
  "BROWS, BUT BETTER": "CEJAS AÚN MEJORES",
  "EYE GAME STRONG": "MIRADA DE IMPACTO",
  "TINTED TO GO": "TINTE PARA LLEVAR",
  "GLOSS IT BETTER": "BRILLO SIN LÍMITES",
  "IT'S MATTE TO LAST": "MATE DE LARGA DURACIÓN",
};

export const productTranslationsSpanish: Record<string, ProductTranslation> = {
  "ALTERA LIP TINT": { description: "Color para labios innovador que pasa de un acabado brillante a uno suave y difuminado con una sola aplicación.", claims: ["Difumina las líneas", "Tinte duradero", "Color intenso"] },
  "ELIXIR VELVET-SHINE SWITCHING LIP CREAM": { description: "Crema labial ligera e hidratante con dos acabados en un solo producto.", claims: ["2 acabados", "Color intenso", "Súper cómodo"] },
  "ETERNAL LIP MATTE": { description: "Labial mate de pigmentación intensa, resistente a la transferencia y al agua hasta por 24 horas.", claims: ["Mate intenso", "Color de alto impacto", "Sensación ligera"] },
  "NEBULA LIP CREAM": { description: "Crema labial de textura aterciopelada mate que no reseca y ayuda a difuminar las líneas de los labios.", claims: ["Mate aterciopelado", "No se transfiere", "Sensación ligera"] },
  "STELLAR DUST LIP STAIN": { description: "Cobertura total en una sola pasada, con textura ligera que fija el pigmento para un color duradero y de mínima transferencia.", claims: ["Tinte superintenso", "Brillo máximo", "Larga duración"] },
  "SPECTRA LIP VINYL": { description: "Labial vinilo resistente a la transferencia, con color ultraintenso y cobertura total en una sola pasada.", claims: ["Color intenso", "Hasta 24 horas", "Súper cómodo"] },
  "ORION CLOUD MATTE LIPSTICK": { description: "Labial mate de alta pigmentación que difumina, brinda cobertura total y resiste la transferencia hasta por 12 horas.", claims: ["Mate difuminado", "Textura suave", "No se transfiere"] },
  "ORBITA 3 IN 1 BLURRING POT": { description: "Fórmula aterciopelada y flexible para ojos, mejillas y labios, con aplicador de silicón de alta precisión.", claims: ["Acabado aterciopelado", "Cobertura modulable", "Aplicador práctico"] },
  "MILKYWAY MELTING LIP BALM": { description: "Bálsamo fundente con brillo 5D, textura cremosa, sensación refrescante, color vibrante y acabado efecto espejo.", claims: ["Brillo 5D", "Suavidad cremosa", "Nutritivo"] },
  "LUNARA 3D LIP GLOSS": { description: "Brillo labial con textura de gel suave y acabado de alto brillo tipo cristal.", claims: ["Efecto 3D", "No pegajoso", "Sensación refrescante"] },
  "APHRODITE EVERLASTING GLOSSY TINT": { description: "Tinte labial brillante de color vivo y larga duración que mantiene los labios cómodos e hidratados.", claims: ["Textura jugosa", "Tinte de fijación acuosa", "Súper cómodo"] },
  "AION SUPERSTAIN LIP TATTOO INK": { description: "Tinte de gel líquido con pigmento tres veces más concentrado para un color intenso hasta por 24 horas.", claims: ["Color intenso", "Efecto tatuaje", "Larga duración"] },
  "UTOPIA GLOW CUSHION": { description: "Cushion ligero y ultrahidratante con luminosidad inmediata, cobertura media a completa y duración de hasta 10 horas.", claims: ["Acabado luminoso", "Suavidad instantánea", "Hidratante"] },
  "LUMINA MATTE CUSHION": { description: "Cushion de cobertura total y sensación ligera para una piel natural e impecable durante todo el día.", claims: ["Acabado natural", "Sensación ligera", "No se oxida"] },
  "OPTIMA POWDER FOUNDATION": { description: "Base de maquillaje en polvo ultraligera que ofrece cobertura total con una sola aplicación.", claims: ["Mate difuminado", "Control de grasa", "No comedogénica"] },
  "PANDORA CHEEK LIQUID BLUSH": { description: "Rubor líquido de alta pigmentación que brinda color intenso con una sola gota.", claims: ["Color intenso", "Fácil de difuminar", "Larga duración"] },
  "FIXION SKIN TINT STICK": { description: "Tinte facial en barra, cremoso y ligero, con cobertura media a completa y acabado de segunda piel hasta por 8 horas.", claims: ["Acabado satinado", "Textura cremosa", "Ligero en la piel"] },
  "ECLIPSE 2 IN 1 FACE CONTOUR": { description: "Barra de contorno facial 2 en 1 con fórmula ultracremosa y color intenso que se desliza uniformemente.", claims: ["Ultracremoso", "De crema a polvo", "Brocha removible"] },
  "VALORA CONCEALER": { description: "Corrector de alta cobertura que disimula ojeras e imperfecciones con un acabado ligero y resistente a los pliegues hasta por 12 horas.", claims: ["Mate suave", "Pigmento intenso", "Hidratante"] },
  "SUPERNOVA SETTING SPRAY": { description: "Fijador con micropartículas de polvo que deja el maquillaje mate al instante y sin brillo.", claims: ["Acabado mate", "Resistente al desgaste", "Control de grasa"] },
  "REVELA BROW MASCARA": { description: "Máscara para cejas con pigmento intenso y fijación de alto desempeño.", claims: ["Color intenso", "Hasta 12 horas", "Sin grumos"] },
  "ILLUMINA EYESHADOW STICK": { description: "Sombra en barra de textura tipo jelly, ligera y fácil de aplicar, con color intenso y alto brillo en una pasada.", claims: ["Textura jelly", "Brillo instantáneo", "Sin residuos"] },
  "DUNE EYELINER": { description: "Delineador con punta fina y precisa para crear trazos definidos y uniformes.", claims: ["Pigmento intenso", "Punta precisa", "Resistente al agua"] },
  "GENESIS EYEBROW PENCIL": { description: "Lápiz para cejas con punta ovalada de precisión para enmarcar, rellenar y definir desde un look natural hasta uno intenso.", claims: ["Acabado natural", "Punta ovalada", "Larga duración"] },
  "NAVI EYESHADOW PALETTE": { description: "Paleta de ocho sombras mate, satinadas y brillantes, fáciles de difuminar y de larga duración.", claims: ["Color intenso", "Fácil de difuminar", "Larga duración"] },
};

export const finishTranslationsTraditionalChinese: Record<string, string> = {
  "SKIN FINISH PERFECTED": "完美底妝",
  "FLAWLESS FLUSHED CHEEKS": "自然紅潤雙頰",
  "BROWS, BUT BETTER": "精緻立體眉型",
  "EYE GAME STRONG": "聚焦迷人眼妝",
  "TINTED TO GO": "隨行持色唇彩",
  "GLOSS IT BETTER": "水光亮澤唇妝",
  "IT'S MATTE TO LAST": "長效霧面唇妝",
};

export const productTranslationsTraditionalChinese: Record<string, ProductTranslation> = {
  "ALTERA LIP TINT": { description: "創新唇彩只需輕輕一抹，即可從水亮光澤轉為柔霧暈染妝效。", claims: ["柔焦唇紋", "長效染唇", "高顯色"] },
  "ELIXIR VELVET-SHINE SWITCHING LIP CREAM": { description: "輕盈保濕的絲絨唇霜，一支即可呈現兩種唇妝效果。", claims: ["雙重妝效", "高顯色", "舒適不乾澀"] },
  "ETERNAL LIP MATTE": { description: "高顯色霧面唇彩，防水且不易沾染，持妝最長可達 24 小時。", claims: ["濃郁霧面", "高顯色", "輕盈質地"] },
  "NEBULA LIP CREAM": { description: "柔滑絲絨霧面唇霜，不乾澀並能柔焦唇紋。", claims: ["絲絨霧面", "不易沾染", "輕盈舒適"] },
  "STELLAR DUST LIP STAIN": { description: "一抹完整遮色，輕盈質地牢牢鎖住色澤，持久且不易沾染。", claims: ["濃郁染唇", "耀眼光澤", "持久顯色"] },
  "SPECTRA LIP VINYL": { description: "不易沾染的鏡光唇釉，一抹即有超飽和色彩與完整遮色。", claims: ["高顯色", "24 小時持妝", "舒適不黏膩"] },
  "ORION CLOUD MATTE LIPSTICK": { description: "高顯色柔焦霧面唇膏，完整遮色且最長 12 小時不易沾染。", claims: ["柔焦霧面", "柔滑質地", "不易沾染"] },
  "ORBITA 3 IN 1 BLURRING POT": { description: "富彈性的絲絨泥質地，可用於眼、頰、唇，搭配精準矽膠刷頭。", claims: ["絲絨柔焦", "可疊加顯色", "便利刷頭"] },
  "MILKYWAY MELTING LIP BALM": { description: "奶油般融化的 5D 光澤潤唇膏，帶來清涼感、鮮明色彩與鏡面亮澤。", claims: ["5D 光澤", "奶油般柔滑", "滋潤雙唇"] },
  "LUNARA 3D LIP GLOSS": { description: "柔滑凝膠質地唇蜜，打造如玻璃般的高亮光澤。", claims: ["3D 豐唇感", "不黏膩", "清涼舒適"] },
  "APHRODITE EVERLASTING GLOSSY TINT": { description: "鮮明水光染唇液，長效持色並維持雙唇舒適水潤。", claims: ["水感質地", "鎖水持色", "舒適保濕"] },
  "AION SUPERSTAIN LIP TATTOO INK": { description: "水感凝膠染唇液，色料濃度提升三倍，鮮明持色最長可達 24 小時。", claims: ["濃郁顯色", "免撕除", "長效持色"] },
  "UTOPIA GLOW CUSHION": { description: "輕盈高保濕光澤氣墊粉餅，立即提亮，提供中度至完整遮瑕，持妝最長 10 小時。", claims: ["水光妝效", "立即柔滑", "高保濕"] },
  "LUMINA MATTE CUSHION": { description: "輕盈高遮瑕氣墊粉餅，全天呈現自然無瑕妝感。", claims: ["自然妝效", "輕盈服貼", "不易氧化"] },
  "OPTIMA POWDER FOUNDATION": { description: "極輕盈粉餅，一抹即可提供完整遮瑕。", claims: ["柔焦霧面", "控油持妝", "不易致粉刺"] },
  "PANDORA CHEEK LIQUID BLUSH": { description: "高顯色液態腮紅，只需一小點即可展現鮮明紅潤色彩。", claims: ["高顯色", "容易暈染", "持久妝效"] },
  "FIXION SKIN TINT STICK": { description: "滑順輕盈的膚色修飾棒，提供中度至完整遮瑕，第二層肌膚般妝效最長 8 小時。", claims: ["緞光妝效", "滑順質地", "輕盈服貼"] },
  "ECLIPSE 2 IN 1 FACE CONTOUR": { description: "二合一修容棒，超滑順配方與飽和色澤，一抹自然融入肌膚。", claims: ["超滑順", "霜轉粉質地", "可拆式刷具"] },
  "VALORA CONCEALER": { description: "高遮瑕遮瑕液，有效修飾黑眼圈與瑕疵，輕盈且最長 12 小時不易卡紋。", claims: ["柔霧妝效", "高顯色遮瑕", "保濕服貼"] },
  "SUPERNOVA SETTING SPRAY": { description: "含均勻細緻粉體的定妝噴霧，立即打造無油光霧面妝效。", claims: ["霧面妝效", "不易脫妝", "控油持妝"] },
  "REVELA BROW MASCARA": { description: "高顯色染眉膏，提供強效定型力。", claims: ["高顯色", "12 小時持妝", "不結塊"] },
  "ILLUMINA EYESHADOW STICK": { description: "輕盈果凍質地眼影棒，容易上妝，一抹即有飽和色澤與高亮光感。", claims: ["果凍質地", "立即閃耀", "不易飛粉"] },
  "DUNE EYELINER": { description: "細緻精準筆尖，輕鬆勾勒俐落均勻眼線。", claims: ["濃黑顯色", "精準筆尖", "防水持妝"] },
  "GENESIS EYEBROW PENCIL": { description: "精準橢圓筆芯，可勾勒、填補並塑造自然或鮮明眉型。", claims: ["自然妝效", "橢圓筆芯", "持久不暈染"] },
  "NAVI EYESHADOW PALETTE": { description: "八色眼影盤，包含霧面、緞光與珠光質地，容易暈染並長效持妝。", claims: ["高顯色", "容易暈染", "持久妝效"] },
};
