export const MEDIAPIPE_ASSET_VERSION = "v0.10.35";
export const MEDIAPIPE_SOURCE_BASE_PATH = "/vendor/mediapipe";
export const MEDIAPIPE_VERSIONED_BASE_PATH =
  `${MEDIAPIPE_SOURCE_BASE_PATH}/${MEDIAPIPE_ASSET_VERSION}`;
export const MEDIAPIPE_ASSET_ROUTE_PATTERN =
  `${MEDIAPIPE_VERSIONED_BASE_PATH}/*`;
export const MEDIAPIPE_BROWSER_CACHE_CONTROL =
  "public, max-age=31536000, immutable";
