export const faqItemsVietnamese = [
  ["Làm thế nào để tham gia chương trình rút thăm Time Phoria?", "Mua ít nhất một sản phẩm Time Phoria tại cửa hàng tham gia, quét mã QR trên tài liệu quảng bá, điền đầy đủ Google Form, tải lên ảnh hóa đơn rõ ràng, dễ đọc rồi gửi biểu mẫu để nhận một lượt tham gia rút thăm."],
  ["Chương trình diễn ra khi nào?", "Chương trình diễn ra từ tháng 7 đến hết tháng 10 năm 2026. Người trúng giải sẽ được công bố vào tháng 11 năm 2026 qua tài khoản Instagram chính thức của Time Phoria."],
  ["Ai có thể tham gia?", "Chương trình dành cho tất cả công dân Indonesia. Người trúng giải du lịch quốc tế phải từ đủ 17 tuổi."],
  ["Chương trình áp dụng ở đâu?", "Chương trình chỉ áp dụng cho giao dịch mua trực tiếp tại cửa hàng bán sản phẩm Time Phoria và có trưng bày tài liệu quảng bá chương trình. Không áp dụng tại các chuỗi bán lẻ Modern Trade (MT) như Guardian, Watsons, Dandan và các cửa hàng MT khác."],
  ["Cần mua tối thiểu bao nhiêu?", "Cần mua ít nhất một sản phẩm Time Phoria."],
  ["Mua nhiều sản phẩm có tăng cơ hội trúng giải không?", "Có. Mỗi sản phẩm Time Phoria được mua tương ứng với một lượt rút thăm. Ví dụ, hai sản phẩm được hai lượt và năm sản phẩm được năm lượt."],
  ["Một hóa đơn có thể dùng nhiều lần không?", "Không. Mỗi hóa đơn chỉ được dùng để đăng ký một lần."],
  ["Tôi cần cung cấp những thông tin gì?", "Người tham gia phải điền đầy đủ thông tin được yêu cầu trong Google Form và tải lên ảnh hóa đơn rõ ràng. Hãy kiểm tra kỹ trước khi gửi vì thông tin đã gửi không thể chỉnh sửa."],
  ["Nếu ảnh hóa đơn không rõ thì sao?", "Hóa đơn bị mờ, hư hỏng, thiếu thông tin, đã chỉnh sửa hoặc không đọc được có thể bị coi là không hợp lệ. Hãy giữ hóa đơn gốc đến khi chương trình kết thúc vì ban tổ chức có thể yêu cầu để xác minh."],
  ["Người trúng giải được chọn như thế nào?", "Tất cả người trúng giải được chọn ngẫu nhiên bằng hình thức rút thăm."],
  ["Kết quả được công bố như thế nào?", "Người trúng giải được công bố trên Instagram chính thức của Time Phoria và được đội ngũ chính thức liên hệ để xác minh. Người trúng giải phải xác nhận trong vòng bốn ngày theo lịch kể từ khi được liên hệ. Nếu quá hạn, giải thưởng sẽ bị hủy và ban tổ chức có thể rút thăm lại."],
  ["Có những giải thưởng chính nào?", "Giải thưởng gồm hai chuyến đi Seoul, ba chuyến đi Bangkok, vàng, đồng hồ thông minh và phiếu mua hàng Alfamart. Ban tổ chức sẽ công bố loại, thông số và giá trị của một số giải thưởng."],
  ["Giải du lịch bao gồm những gì?", "Mỗi người trúng giải nhận một gói du lịch dành cho một người, gồm vé máy bay khứ hồi từ Jakarta đến điểm đến, khách sạn, các bữa ăn theo lịch trình, thị thực nếu cần và các dịch vụ khác trong gói của đối tác du lịch."],
  ["Giải du lịch không bao gồm những gì?", "Giải không bao gồm chi phí đi lại giữa nơi cư trú của người trúng giải và Jakarta, tiền tiêu vặt, chi phí cá nhân, mua sắm cá nhân hoặc các chi phí ngoài gói du lịch."],
  ["Nếu tôi sống ngoài Jakarta thì sao?", "Người trúng giải sống ngoài Jakarta tự chi trả chi phí đến Jakarta và trở về nơi cư trú."],
  ["Tôi có cần hộ chiếu không?", "Có. Người trúng giải phải có hộ chiếu còn hiệu lực theo yêu cầu đi lại quốc tế. Người trúng giải tự chịu trách nhiệm làm mới hoặc gia hạn hộ chiếu."],
  ["Chuyến đi khởi hành khi nào?", "Các chuyến đi dự kiến diễn ra vào tháng 1 đến tháng 2 năm 2027. Ngày khởi hành tùy thuộc vào lịch của đối tác du lịch và thỏa thuận với người trúng giải."],
  ["Tôi có thể đi cùng người khác không?", "Giải du lịch chỉ dành cho một người trúng giải và không bao gồm người đi cùng. Người trúng giải tự chi trả mọi chi phí bổ sung cho người đi cùng theo quy định của đối tác du lịch."],
  ["Có thể chuyển nhượng giải du lịch không?", "Có. Người trúng giải có thể chuyển giải du lịch cho người khác nếu thông báo cho ban tổ chức trước khi tiến hành sắp xếp chuyến đi."],
  ["Nếu tôi không thể đi du lịch thì sao?", "Người trúng giải có thể chọn nhận tiền mặt tương đương giá trị gói du lịch do Time Phoria xác định. Người trúng giải chịu trách nhiệm nộp thuế đối với khoản tiền này theo quy định hiện hành."],
  ["Có thể đổi giải thưởng hoặc nhận tiền mặt không?", "Không thể đổi giải thưởng hoặc quy đổi thành tiền mặt, trừ trường hợp giải du lịch được nêu tại câu hỏi số 20."],
  ["Ai chịu thuế giải thưởng?", "Người trúng giải chịu mọi khoản thuế đối với giải thưởng theo quy định hiện hành."],
  ["Cần gì khi xác minh giải thưởng?", "Người trúng giải phải xuất trình thẻ căn cước quốc gia hoặc giấy tờ tùy thân chính thức còn hiệu lực, thông tin trùng khớp với đăng ký và hóa đơn mua hàng gốc nếu ban tổ chức yêu cầu."],
];

export const termsItemsVietnamese = [
  "Chương trình diễn ra từ tháng 7 đến hết tháng 10 năm 2026.",
  "Chương trình chỉ áp dụng cho giao dịch mua sản phẩm Time Phoria trực tiếp tại cửa hàng tham gia và có trưng bày tài liệu quảng bá chương trình.",
  "Mỗi sản phẩm Time Phoria được mua tương ứng với một lượt rút thăm.",
  "Mỗi hóa đơn mua hàng chỉ được dùng để đăng ký một lần.",
  "Người tham gia phải cung cấp thông tin chính xác, đầy đủ trong Google Form.",
  "Ban tổ chức có quyền xác minh thông tin người tham gia, chứng từ mua hàng và danh tính người trúng giải.",
  "Người tham gia sẽ bị loại nếu dùng hóa đơn giả hoặc đã chỉnh sửa; cung cấp thông tin sai; dùng tài khoản Instagram giả hoặc không hợp lệ; gửi tin nhắn rác hoặc gây gián đoạn chương trình; không thể liên hệ hoặc không xác nhận trong bốn ngày theo lịch; hoặc không xuất trình giấy tờ cần thiết khi xác minh.",
  "Quyết định của ban tổ chức trong toàn bộ chương trình, bao gồm xác minh, rút thăm và xác định người trúng giải, là quyết định cuối cùng và không thể khiếu nại.",
  "Người trúng giải chịu mọi khoản thuế đối với giải thưởng theo quy định hiện hành.",
  "Người trúng giải du lịch phải có hộ chiếu còn hiệu lực và đáp ứng yêu cầu đi lại quốc tế.",
  "Giải du lịch không bao gồm chi phí đến Jakarta, tiền tiêu vặt, chi phí cá nhân và chi phí ngoài gói du lịch.",
  "Nếu người trúng giải chọn không đi du lịch, ban tổ chức có thể trao tiền mặt tương đương giá trị gói du lịch. Người trúng giải chịu thuế đối với khoản tiền này.",
  "Có thể chuyển nhượng giải du lịch cho người khác nếu thông báo cho ban tổ chức trước ngày khởi hành.",
  "Ban tổ chức có thể thay đổi lịch trình, cách thức chương trình hoặc loại giải thưởng bằng giải có giá trị tương đương khi xảy ra sự kiện ngoài tầm kiểm soát (bất khả kháng), gồm thay đổi quy định, hủy chuyến đi, chính sách của chính phủ hoặc các tình huống bất khả kháng khác.",
  "Khi tham gia, người tham gia được coi là đã đọc, hiểu và đồng ý với toàn bộ điều khoản và điều kiện áp dụng.",
];

export const giveawayDisclaimerVietnamese = "Cảnh giác với hành vi lừa đảo mạo danh Time Phoria. Thông tin chính thức về chương trình rút thăm Time Phoria chỉ được công bố qua tài khoản Instagram và các kênh liên hệ chính thức của Time Phoria. Time Phoria không thu phí tham gia hoặc nhận giải từ người tham gia hay người trúng giải.";
